/**
 * The Pi extension source — the single string installed into Pi's extension
 * directory (`~/.pi/agent/extensions/fil.ts` or `<project>/.pi/extensions/fil.ts`).
 *
 * This file MUST stay a pure string template so the deep logic in
 * `enforcement.ts` remains unit-testable without the Pi runtime installed.
 * Pi loads it via jiti, so any `import` from npm packages resolves at runtime
 * through the extension directory's `node_modules/` (or Pi's own tree).
 */

/**
 * Render the complete Pi extension source code as a string.
 *
 * The output is a self-contained ESM TypeScript module that Pi loads through
 * jiti. It:
 *   1. reads `.fil/run.json` from the project (or the user-level mirror);
 *   2. on `resources_discover`, surfaces Phase skills by name through project/user precedence;
 *   3. on `before_agent_start`, prepends the Phase's instructions + Fil context as a system-prompt delta;
 *   4. on every load, calls `setActiveTools(allowedTools)` so the Tier-0 advisory list matches the contract;
 *   5. on `tool_call`, blocks any tool not in `allowedTools` (Tier-1 enforcement — defense in depth).
 */
export function renderPiExtensionSource(): string {
  return `// Generated by @fil/pi-adapter. Do not edit by hand — re-run \`fil init\`.
import { existsSync, readFileSync } from "node:fs";
import { dirname, isAbsolute, join } from "node:path";
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";

const RUN_JSON_REL = ".fil/run.json";

function readProjection(cwd: string) {
  const path = join(cwd, RUN_JSON_REL);
  if (!existsSync(path)) return null;
  try {
    const parsed = JSON.parse(readFileSync(path, "utf8"));
    if (parsed && parsed.status === "active" && parsed.phaseConfig) return parsed;
  } catch {}
  return null;
}

function userFilDir() {
  return join(process.env.HOME ?? process.env.USERPROFILE ?? "", ".fil");
}

function resolveSkillAt(dir, name) {
  if (!name || name.length === 0 || name.length > 64) return null;
  if (!/^[a-z0-9-]+$/.test(name)) return null;
  if (name.startsWith("-") || name.endsWith("-")) return null;
  if (name.includes("--")) return null;
  return join(dir, name, "SKILL.md");
}

function isSafeSegment(name) {
  return resolveSkillAt(".", name) !== null;
}

function enforce(projection, cwd) {
  if (!projection || projection.status !== "active") return null;
  const cfg = projection.phaseConfig || {};
  const projectRoot = cwd;
  const userSkillsRoot = join(userFilDir(), "skills");
  const skillPaths = [];
  for (const name of cfg.skills || []) {
    if (!isSafeSegment(name)) continue;
    const projectCandidate = resolveSkillAt(join(projectRoot, ".fil/skills"), name);
    if (projectCandidate && existsSync(projectCandidate)) {
      skillPaths.push(projectCandidate);
      continue;
    }
    const userCandidate = resolveSkillAt(userSkillsRoot, name);
    if (userCandidate && existsSync(userCandidate)) {
      skillPaths.push(userCandidate);
    }
  }
  return {
    phase: projection.phase,
    phases: projection.phases || [projection.phase],
    allowedTools: cfg.allowedTools || [],
    skillPaths,
    systemPrompt: composeSystemPrompt(projection),
  };
}

function composeSystemPrompt(projection) {
  const cfg = projection.phaseConfig || {};
  const lines = [];
  lines.push("# Fil — Phase instructions");
  lines.push("");
  lines.push(String(cfg.instructions || "").trim());
  lines.push("");
  lines.push("# Fil — context");
  if ((cfg.context && cfg.context.files || []).length > 0) {
    lines.push("Files in scope:");
    for (const file of cfg.context.files) lines.push(\`  - \${file}\`);
  }
  if (cfg.context && cfg.context.notes && cfg.context.notes.trim().length > 0) {
    lines.push("");
    lines.push("Notes:");
    lines.push(cfg.context.notes.trim());
  }
  if (cfg.context && cfg.context.priorResults && cfg.context.priorResults.length > 0) {
    lines.push("");
    lines.push("Receipts from prior Phases:");
    for (const r of cfg.context.priorResults) lines.push(\`  - \${r}\`);
  }
  lines.push("");
  lines.push("# Fil — current Run");
  lines.push(\`Run \${projection.runId} · change "\${projection.change}" · flow "\${projection.flowName}"\`);
  lines.push(
    "Phase " +
      (projection.phases && projection.phases.length > 1
        ? projection.phases.join(", ") + " (parallel)"
        : projection.phase) +
      " · actor " +
      projection.actorMode,
  );
  lines.push("Gate (to advance): " + describeGate(cfg.gate && cfg.gate.type));
  lines.push("Advance via \`fil next\` — the gate runs an external test, not the agent's say-so.");
  return lines.join("\\n");
}

function describeGate(type) {
  switch (type) {
    case "shell":
      return "shell command (exit 0 = pass)";
    case "testsPass":
      return "test suite (exit 0 = pass)";
    case "human":
      return "human confirmation prompt";
    default:
      return type || "n/a";
  }
}

export default function filPiExtension(pi) {
  let cachedEnforcement = null;
  function refresh(cwd) {
    const projection = readProjection(cwd);
    cachedEnforcement = projection ? enforce(projection, cwd) : null;
  }

  pi.on("session_start", async (event, ctx) => {
    refresh(ctx.cwd);
    if (!cachedEnforcement) return;
    pi.setActiveTools(cachedEnforcement.allowedTools);
    ctx.ui.setStatus(
      "fil-phase",
      ctx.ui.theme?.fg?.("accent", \`fil · \${cachedEnforcement.phase}\`) ?? \`fil · \${cachedEnforcement.phase}\`,
    );
  });

  pi.on("resources_discover", async (event) => {
    if (!cachedEnforcement) return;
    return { skillPaths: cachedEnforcement.skillPaths };
  });

  pi.on("before_agent_start", async (event) => {
    if (!cachedEnforcement) return;
    return {
      systemPrompt: cachedEnforcement.systemPrompt + "\\n\\n" + event.systemPrompt,
    };
  });

  pi.on("tool_call", async (event) => {
    if (!cachedEnforcement) return;
    // Fail-closed: an empty allowedTools set means the Phase permits no
    // tools at all. Block every tool call with a clear reason, mirroring
    // session_start's setActiveTools([]) (which surfaces the same intent
    // to the UI).
    if (cachedEnforcement.allowedTools.length === 0) {
      return {
        block: true,
        reason: "Fil Phase '" + cachedEnforcement.phase + "' permits no tools.",
      };
    }
    if (!cachedEnforcement.allowedTools.includes(event.toolName)) {
      return {
        block: true,
        reason:
          "Fil Phase '" + cachedEnforcement.phase + "' disallows tool '" +
          event.toolName + "'. Allowed: " +
          cachedEnforcement.allowedTools.join(", "),
      };
    }
    return undefined;
  });
}
`;
}
