/**
 * The Claude Code PreToolUse hook source — the single string installed by the
 * adapter and invoked by Claude Code before every tool call.
 *
 * This file MUST stay a pure string template so the deep logic in
 * `enforcement.ts` (and `decideToolUse`) remains unit-testable without Claude
 * Code installed. Claude Code spawns it via `node <path>`, feeding the hook
 * event JSON on stdin.
 *
 * Claude Code's PreToolUse contract:
 *   - stdin:  `{ tool_name, tool_input, cwd, session_id, ... }`
 *   - allow:  exit 0 with no stdout (normal permission flow proceeds)
 *   - deny:   exit 0 with stdout JSON
 *             `{ "hookSpecificOutput": { "hookEventName": "PreToolUse",
 *               "permissionDecision": "deny", "permissionDecisionReason": "…" } }`
 *
 * The hook is dormant (allows everything) unless `.fil/run.json` reports an
 * active Run, so Fil never interferes with Claude outside a steered Phase.
 */

/** Render the complete, self-contained PreToolUse hook script as a string. */
export function renderPreToolUseHookSource(): string {
  return `// Generated by @fil/claude-adapter. Do not edit by hand — re-run \`fil init\`.
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

const RUN_JSON_REL = ".fil/run.json";

function readProjection(projectDir) {
  const path = join(projectDir, RUN_JSON_REL);
  if (!existsSync(path)) return null;
  try {
    const parsed = JSON.parse(readFileSync(path, "utf8"));
    if (parsed && parsed.status === "active" && parsed.phaseConfig) return parsed;
  } catch {}
  return null;
}

// Fail-closed tool-use decision, mirroring @fil/claude-adapter's decideToolUse.
function decide(projection, toolName) {
  if (!projection || projection.status !== "active") return null;
  const allowedTools = (projection.phaseConfig && projection.phaseConfig.allowedTools) || [];
  const phase = projection.phase || "(unknown phase)";
  if (allowedTools.length === 0) {
    return "Fil Phase '" + phase + "' permits no tools.";
  }
  if (!allowedTools.includes(toolName)) {
    return "Fil Phase '" + phase + "' disallows tool '" + toolName + "'. Allowed: " + allowedTools.join(", ") + ".";
  }
  return null;
}

let input = "";
for await (const chunk of process.stdin) input += chunk;

let payload = {};
try { payload = JSON.parse(input || "{}"); } catch {}
const toolName = payload.tool_name || "";
const projectDir = process.env.CLAUDE_PROJECT_DIR || payload.cwd || process.cwd();

const projection = readProjection(projectDir);
const reason = decide(projection, toolName);
if (reason) {
  console.log(JSON.stringify({
    hookSpecificOutput: {
      hookEventName: "PreToolUse",
      permissionDecision: "deny",
      permissionDecisionReason: reason,
    },
  }));
}
// exit 0 in both cases: stdout JSON denies; silence allows.
`;
}
